### ISSUE TITLE
Can't not find module ...SyntaxHighlighterTextView.ios

### ISSUE THREAD

**Issue by michaeldong** [shirakaba/nside#6]
Follow your setup steps.

when i run   ./node_modules/.bin/tsc --watch
But tips:
Can't not find module nativescript-syntax-highlighter/react/SyntaxHighlighterTextView.ios

i check out my nodemodules and find nativescript-syntax-highlighter folder, but does not exist react/SyntaxHighlighterTextView.ios

![image](https://user-images.githubusercontent.com/1925773/75977126-acb9d300-5f16-11ea-9797-9ee869484be7.png)

**Comment by shirakaba** [comment]
@michaeldong My apologies – I'm currently actively making changes to that plugin (the update to iOS 13 broke it, and possibly all components extending NativeScript TextView).

The instructions for cloning nativescript-syntax-highlighter are currently:

```sh
git clone git@github.com:shirakaba/nativescript-syntax-highlighter.git
```

For this current version of nside, they should actually be:

```sh
git clone git@github.com:shirakaba/nativescript-syntax-highlighter.git
cd nativescript-syntax-highlighter
git checkout extend-text-view
```

The instructions that follow are all still correct. After checking out the `extend-text-view` branch of NativeScript Syntax Highlighter above, make sure to run this step again to install it into the `nside` project:

```sh
# Install NS:IDE dependencies
## In the root directory for this project (nside), run this command:
npm install
```

A warning: I still haven't found a way to get the TextViews working completely since iOS 13. I believe this is a NativeScript Core bug (not a React NativeScript bug, nor a bug of NS:IDE), and am currently asking for advice from NativeScript professionals on this matter. I've lost a whole weekend investigating it, however, so progress is slow.

Specifically, you'll find that the TextViews (including SyntaxHighlighterView, which extends TextView) may only display one line, or disappear completely if you focus another TextView after scrolling down on the current TextView. I find that you can get full usage out of them by scrolling them back to the top, rotating the device once, then back, then scrolling back down to where you were before.

Once I've managed to fix the SyntaxHighlighterView (and TextView) behaviour, I'll merge the SyntaxHighlighterView changes into its master branch and the current instructions in the NS:IDE readme will be correct again.

**Comment by shirakaba** [comment]
@michaeldong Also, if you need any help setting up NS:IDE, I can walk you through the process on Slack in the #react channel:

https://app.slack.com/client/T0L97VCSY/CJ2B77CJ1/thread/G0LLUAZF0-1583342304.287800

**Comment by michaeldong** [comment]
This is truly above and beyond! 
Thank you!
